export const categoryConstants ={
    ADD_CATEGOTY :"ADD_CATEGORY",
DELETE_CATEGORY:"DELETE_CATEGORY",
UPDATE_CATEGORY:"UPDATE_CATEGORY",
    
LIST_CATEGORIES:"LIST_CATEGPRIEES"
}

export const courseConstants ={
    ADD_COURSE:"ADD_COURSE",
DELETE_COURSE:"DELETE_COURSE",
UPDATE_COURSE:"UPDATE_COURSE",
LIST_COURSES:"LIST_COURSES"
}
export const roleConstants ={
    ADD_ROLE:"ADD_ROLE",
DELETE_ROLE:"DELETE_ROLE",
UPDATE_ROLE:"UPDATE_ROLE",
LIST_ROLES:"LIST_ROLES"
}
export const userConstants ={
   
DELETE_USER:"DELETE_USER",
UPDATE_USER:"UPDATE_USER",
LIST_USERS:"LIST_USERS",

}

export const requestConstants ={
    ADD_REQUEST:"ADD_REQUEST",
    DELETE_REQUEST:"DELETE_REQUEST",
    UPDATE_REQUEST:"UPDATE_REQUEST",
    LIST_REQUESTS:"LIST_REQUESTS"
    }
    export const topicConstants ={
        ADD_TOPIC:"ADD_TOPIC",
        DELETE_TOPIC:"DELETE_TOPIC",
        UPDATE_TOPIC:"UPDATE_TOPIC",
        LIST_TOPICS:"LIST_TOPICS"
    }